name: AutocompleteMetadata

on:
  pull_request_target:
    paths:
      - 'Molecules/membrane/**/metadata.yaml'
      - 'Molecules/solution/**/metadata.yaml'

permissions:
  contents: read
  pull-requests: write

jobs:
  add-metadata:
    runs-on: ubuntu-latest

    container:
      image: nmrlipids/core
      options: --user 1001:118
      env:
        FMDL_DATA_PATH: ${{ github.workspace }}/BilayerData

    steps:
      - name: Checkout BilayerData
        uses: actions/checkout@v5
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          path: BilayerData
          persist-credentials: false
      
      - name: Checkout Databank
        uses: actions/checkout@v5
        with:
          repository: NMRlipids/FAIRMD_lipids
          ref: main
          path: Databank
          persist-credentials: false
    

      - name: Install the gh cli
        uses: ksivamuthu/actions-setup-gh-cli@v3
        with:
          version: 2.83.0

      - name: Install Databank dependencies
        working-directory: Databank
        run: |
          pip install .

      - name: Find changed metadata.yaml files
        id: files
        working-directory: BilayerData
        run: |
          changed_files=$(gh pr diff ${{ github.event.pull_request.number }} --repo ${{ github.repository }} \
            | grep -E 'diff --git a/Molecules/(membrane|solution)/[^/]+/metadata\.yaml' \
            | awk '{print $3}' \
            | sed 's|^a/||' \
            | grep -E '^Molecules/(membrane|solution)/[^/]+/metadata\.yaml$' || true)
          changed_files_list=$(echo "$changed_files" | tr '\n' ' ' | xargs)
          echo "changed_files=${changed_files_list}" >> $GITHUB_OUTPUT
          echo "Changed files: $changed_files_list"

      - name: Run AddMetadata.py and create suggestions
        if: steps.files.outputs.changed_files != ''
        working-directory: BilayerData
        run: |
          echo "${{ steps.files.outputs.changed_files }}" | xargs -n1 -I{} python ../Databank/developer/AutocompleteMetadata.py "{}"

      - name: Suggest changes on PR
        if: steps.files.outputs.changed_files != ''
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: addmetadata
          github_token: ${{ secrets.GITHUB_TOKEN }}
